### ISSUE TITLE
Improve format specification headings

### ISSUE THREAD

**Issue by hagenw** [audeering/audformat#10]
Our current naming of the sections in the documentation makes totally sense for the navigation menu:

![image](https://user-images.githubusercontent.com/173624/103510597-d5c43080-4e65-11eb-85da-ce4e15293fae.png)

But it becomes less obvious if you navigate on a small screen where you don't see that menu and use the next prev buttons, because then you will see a page called `Introduction` in the middle of the documentation and you have no clue that you are now in a new chapter.

This problem is not urgent, and I also don't have a good idea how to fix this.

**Comment by hagenw** [comment]
One solution to this problem would be to simply remove the "Introduction" section under "FORMAT SPECIFICATION" as it is not really needed.

**Comment by frankenjoe** [comment]
@hagenw I don't fully understand the problem :) But probably because I never viewed the documentation on a small screen. However, it sounds rather like a general problem we have with all our packages. If so, it should probably be solved by the scheme.

**Comment by hagenw** [comment]
The issue describes the problem that TOC tree captions like "GETTING STARTED" and "FORMAT SPECIFICATION" are only visible in the TOC tree, but not on a single page. If you are on a small screen and you use the "Next" and "Previous" buttons to navigate through the documentation you will never see them, but simply see a heading "Introduction" in the middle of the documentation and you are wondering what is now introduced.

But I agree that this is more a scheme issue and also not very relevant/urgent.

Will close this issue.
