### ISSUE TITLE
Speed up conversion to segmented table without NaT

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audformat#111]
When converting from a `filewise` to a `segmented` index we usually call `utils.to_segmented_index()` where we have the option to set the end of the segments to the file duration. This can be a bottleneck for large tables since the file duration has to be calculated for every file. However, usually we get our tables from a database that we load with [audb](https://github.com/audeering/audb) where the duration of every file is stored in the dependency table. So I wonder if we find a way to benefit from this information to speed up the conversion to segmented tables.

Possible solution might be that `audb` attaches a table with fie duration to the `Database` object it returns and we add a `segmented` option to `Table.get()` and `Column.get()`. If set to `True`, we return a segmented index where we can now access the file duration directly from the attached duration table.

**Comment by frankenjoe** [comment]
As mentioned in #113 coding should be straight-forward, so it's basically a question which design we want to choose. I see two main solutions:

### Solution 1: private member

Add private member  `Database._duration`, which stores a table with duration per file and which is set by `audb`. To also make the information accessable to the user, we could add `Database.duration(file)`.

### Solution 2: column in db['files']

If it does not already exist, `audb` adds `db['files']['duration']`. Since a user will see the column, there is no need to extend the interface.

@hagenw which solution would you prefer or do you see another solution?

**Comment by hagenw** [comment]
I would go for "Solution 1" as I don't think that the actual tables should be changed.

I also don't see a direct need for making it accessible to the user. As a first step I would update `audformat.utils.to_segmented_index(allow_nat=False)` that it first checks `Database._duration()` and only uses `audiofile.duration()` if information is missing. A user can always extend a database, so we can not rely only `Database._duration()`.

Above you proposed to maybe add a `segmented` argument to our `get()` methods. At the moment I'm not completely convinced by that. Having to use ``audformat.utils.to_segmented_index()` instead highlights more that this operation is not trivial and might take some time. But we can discuss about this also after we have implemented using the duration values from the dependency table.

**Comment by hagenw** [comment]
There is one advantage I see in adding `Database.duration(file)` though. If it is called on a file without an entry in `Database._duration` it could add it there and afterwards it will be faster when called again, which is not the case for `audiofile.duration(os.path.join(db.root), file))`.

**Comment by frankenjoe** [comment]
> As a first step I would update `audformat.utils.to_segmented_index(allow_nat=False)`

I don't see this work, the function does not know about `Database`.
