### ISSUE TITLE
Database.update() with copy_media=True ends up with tmp folder

### ISSUE THREAD

**Issue by hagenw** [audeering/audformat#112]
I have not created a minimal example yet, but when trying to add new data to `mozillacommonvoice` into the `build` dir I run the following command:
```python
db.update(db_new, copy_media=True)
```
Afterwards, all the new data should also be stored inside `build`. Instead it is stored under `build~`.

**Comment by hagenw** [comment]
This seems not to be related to our latest changes, as it also happens for me with version 0.11.6 of `audformat`

**Comment by hagenw** [comment]
I think this is no `audformat` bug, but has its cause in https://github.com/audeering/audb/issues/134

**Comment by frankenjoe** [comment]
As far as I see the problem was fixed in https://github.com/audeering/audb/pull/138.
