### ISSUE TITLE
Input type for audformat.segmented_index()

### ISSUE THREAD

**Issue by hagenw** [audeering/audformat#12]
In the documentation the following input types are allowed for `starts` and `ends`:

![image](https://user-images.githubusercontent.com/173624/103761861-a523f880-5017-11eb-9124-679322e06840.png)

But it also works for integers:

```python
>>> audformat.segmented_index(['a.wav', 'a.wav'], [0, 1], [1, 2])
MultiIndex([('a.wav',           '0 days 00:00:00', ...),
            ('a.wav', '0 days 00:00:00.000000001', ...)],
           names=['file', 'start', 'end'])
```

and floats as well (besides that the position after the comma is no longer considered):

```python
>>> audformat.segmented_index(['a.wav', 'a.wav'], [0., 1.1], [1., 2.1])
MultiIndex([('a.wav',           '0 days 00:00:00', ...),
            ('a.wav', '0 days 00:00:00.000000001', ...)],
           names=['file', 'start', 'end'])
```

I would propose that we add `int` as type as well and add a word to the documentation that this is then handled as `ns`.

**Comment by hagenw** [comment]
Another more user friendly solution might be to add integer and float as supported inputs and tread them as time in seconds and convert to timedelta under the hood.

**Comment by frankenjoe** [comment]
I would not include `float` as a supported type.

**Comment by frankenjoe** [comment]
Ah, overlooked your last comment. Yes, if we treat `float` as seconds it makes sense.
