### ISSUE TITLE
assert_index() can be a bottleneck

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audformat#125]
See https://github.com/audeering/audb/pull/149#issuecomment-971586169

Possible solutions:

* Removing it everywhere and leave it completely to the user to call assert_index().
* Separate `obj.has_duplicates` from `assert_index()` (e.g. add `assert_no_duplicates()`) and call it only if really needed.
*  Add an argument to `assert_index()` (and functions that call it) to disable checking for duplicates.

**Comment by hagenw** [comment]
This is especially important in functions that could be called inside a loop and where a user would expect that they are fast, e.g. `audformat.index_type()`:

```python
>>> import timeit
>>> timeit.timeit("type(index)", setup="import audformat; index = audformat.filewise_index([f'f{n}' for n in range(1000000)])")
0.044285469004535116
>>> timeit.timeit("audformat.index_type(index)", setup="import audformat; index = audformat.filewise_index([f'f{n}' for n in range(1000000)])")
8.92328781800461
```
