### ISSUE TITLE
audformat.Database docstring not explicit on how to provide languages

### ISSUE THREAD

**Issue by hagenw** [audeering/audformat#128]
I looked at the languages that are included in `mozillacommonvoice` 2.0.0 and saw `German, fra`. I was wondering howto provide the language value in order to avoid such problems, but looking at https://audeering.github.io/audformat/api.html#database it just states 

![image](https://user-images.githubusercontent.com/173624/142579616-ac49e6be-23f3-4ecf-912a-1de2102e4409.png)

Would be nice if we add a statement there in which format you should provide the languages.

In the example above I provided `fra` as `fr`.

**Comment by frankenjoe** [comment]
As far as I remember we call [utils.map-language](https://audeering.github.io/audformat/api-utils.html#map-language) in the constructor, if you look at the docstring example of [Database](https://audeering.github.io/audformat/api.html#database) you can see that this maps `['English', 'de']` to `[eng, deu]`.

**Comment by frankenjoe** [comment]
> in `mozillacommonvoice` 2.0.0 and saw `German, fra`

I guess this was still done with the old `audb' where we did not use that mapping function.
