### ISSUE TITLE
When to remove deprecated root argument in testing.create_audio_files()?

### ISSUE THREAD

**Issue by hagenw** [audeering/audformat#153]
In `audformat.testing.create_audio_files()` we have marked the `root` argument as deprecated, see https://github.com/audeering/audformat/blob/8ceaf75f365eaf5f8cd079f5889ef5bfdda2ad49/audformat/core/testing.py#L180-L186

But so far we have not mentioned when it will be removed. Was our original goal to never remove it to not break code, or should we add a message that we remove it in version 1.0.0.

If we are not planning to remove it, then we should maybe at a note at https://audeering.github.io/audformat/api-testing.html#create-audio-files and mention that `root` is deprecated and will have no effect instead of simply not listing it in the parameters.

**Comment by frankenjoe** [comment]
I suggest we remove it with 1.0.0
