### ISSUE TITLE
to_segmented_index() returns wrong index type for end

### ISSUE THREAD

**Issue by hagenw** [audeering/audformat#17]
Compare the output of:

```python
>>> idx = audformat.segmented_index('a')
>>> idx
MultiIndex([('a', '0 days', NaT)],
           names=['file', 'start', 'end'])
>>> idx.get_level_values('end')
TimedeltaIndex([NaT], dtype='timedelta64[ns]', name='end', freq=None)
```
with
```python
>>> idx = audformat.utils.to_segmented_index(audformat.filewise_index('a'))
>>> idx
MultiIndex([('a', '0 days', 'NaT')],
           names=['file', 'start', 'end'])
>>> idx.get_level_values('end')
DatetimeIndex(['NaT'], dtype='datetime64[ns]', name='end', freq=None)
```

This is very unfortunate as it makes it much harder to work with the indices in other applications, e.g. for example how to easily calculate a duration if the type of end can be different.

**Comment by frankenjoe** [comment]
I know this is nasty. What I usually do to avoid that 'NaT'  is interpreted as `datatime` is `pd.to_timedelta(pd.NaT)`.

**Comment by hagenw** [comment]
> I know this is nasty. What I usually do to avoid that `NaT` is interpreted as `datetime` is `pd.to_timedelta(pd.NaT)`.

I tried this at https://github.com/audeering/audformat/blob/master/audformat/core/utils.py#L348 but it did not help, so I created the solution presented in #18

**Comment by frankenjoe** [comment]
OK! Good to know this fix does not always help.
