### ISSUE TITLE
Add support for using schemes in labels

### ISSUE THREAD

**Issue by hagenw** [audeering/audformat#181]
Currently we have the problem that we cannot define schemes for attributes defined inside labels, e.g.

```python
labels = {
  's1': {'age': 30, 'gender': 'female'},
  's2': {'age': 50, 'gender': 'male'},
}
db.schemes['speaker'] = audformat.Scheme(labels=labels)
```
In the above example it would be nice to have the schemes `age` and `gender` as well in order to
* get a correct overview of what schemes are in the database
* avoid typos like `'Male'`

Possible changes need to be done in a backward compatible way.

---

One solution might be to introduce an additional `audformat.Labels` class that can be handed as `labels` argument to `Schemes()` in addition to a list or a dict. This class could then assign schemes to the different keys.

**Comment by frankenjoe** [comment]
We should be able to solve this once we have integrated the new `MiscTable` class, see https://github.com/audeering/audformat/pull/179#issuecomment-1123296715

**Comment by hagenw** [comment]
Done in https://github.com/audeering/audformat/pull/201
