### ISSUE TITLE
Deprecate Table.df

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audformat#182]
Currently there are two ways to access the underlying `DataFrame` of a `Table` object.

1.`Table.get()`
2. `Table.df`

By default `Table.get()` returns a copy, which is safer since the user is not supposed to directly manipulate `Table.df`. However, the user can also do `Table.get(copy=False)`, which is basically the same as `Table.df`. Targeting `1.0.0` we should think about deprecating `Table.df`.

**Comment by hagenw** [comment]
Uh, this will have some big consequences as some users use `Table.df` most of the time.
I see the motivation to force the usage of `Table.get()`, but for just inspecting the content of the table `Table.get(copy=False)` includes way to many chars compared to `Table.df`.

I would vote for stay with the current behavior.

**Comment by frankenjoe** [comment]
Ok, but then I propose we also offer `Misc.df` (see https://github.com/audeering/audformat/pull/179) for symmetry reasons.

In additon I suggest we add a warning that `Table.df` and `Table.get(copy=False)` that it can be used to access the original `DataFrame` object, but that users are not supposed to modify the result. Currently we are very sparse here:

![image](https://user-images.githubusercontent.com/10383417/167852670-b25c19ca-8c50-42f6-a856-64b249057a99.png)

**Comment by hagenw** [comment]
Yes, we should expand the docs.

And with "do not officially allow for `db['table'].df['c'] = s`" I meant we should add `db['table'].df`, but don't provide examples in the doc that you can change the content that way.

So, yes, we should add `Misc.df`.

**Comment by frankenjoe** [comment]
We decided to stay with `.df`.
