### ISSUE TITLE
Difference between TIME and DATE in audformat.define.DataType

### ISSUE THREAD

**Issue by hagenw** [audeering/audformat#19]
Let's assume you would like to store the exact date and time of a recording using `datetime.datetime`, then it is not obvious from the [current documentation](https://audeering.github.io/audformat/api-define.html) what the data type of the scheme should be: `TIME` or `DATE`.

I would assume that `TIME` should cover duration values rather then datetime values, correct?

/cc @agfcrespi

**Comment by frankenjoe** [comment]
Yes, `TIME` measures duration, i.e. is relative, whereas `DATE` defines an absolute point in time.

**Comment by hagenw** [comment]
> Yes, `TIME` measures duration, i.e. is relative, whereas `DATE` defines an absolute point in time.

Good, then I understood it correctly. I will create a pull request adding a little bit more documentation at that point as it is not totally obvious.
