### ISSUE TITLE
Introduce property to audformat.Database to list all tables

### ISSUE THREAD

**Issue by hagenw** [audeering/audformat#191]
Usually the first thing I do after loading a database is calling

```python
list(db.tables)
```

After https://github.com/audeering/audformat/pull/189 is merged and we added `MiscTable` this can become even more complicated:

```python
list(db.tables) + list(db.misc_tables)
```

The question is if we should introduce a property as a short cut for this. Implementation is straightforward, but finding a name and deciding if we should always show misc tables as well isn't.

**Comment by frankenjoe** [comment]
We could use `list(db)` as a shortcut to display all tables?

**Comment by hagenw** [comment]
This might indeed be a solution.
We also don't need to be afraid that this was used before as it simply raised an error (`emodb` example):

```python
>>> list(db)
...
BadKeyError: "Bad key '0', expected one of ['emotion', 'emotion.categories.test.gold_standard', 'emotion.categories.train.gold_standard', 'files']"
```

**Comment by frankenjoe** [comment]
Ok, I propose we tackle it in a separate PR when #189 is merged.
