### ISSUE TITLE
Add MiscTable to the audformat specifications

### ISSUE THREAD

**Issue by hagenw** [audeering/audformat#192]
There is the option to not add `MiscTable` (compare #189) to the official specifications, but as it stores tables under the same name as a normal table, adds entries to the YAML file and will be tightly integrated to our Python implementation I would vote to include it.

At the moment the structure of the specification looks like this

![image](https://user-images.githubusercontent.com/173624/170940956-55cbf43f-4650-4ffe-b51d-a437bc90c803.png)

We could integrate the specifications under "Tables", but at the moment "Tables" is very much focused on filewise or segmented tables, e.g.

---

![image](https://user-images.githubusercontent.com/173624/170941351-a07736b3-5e43-4a5a-8785-61ebebf3fb12.png)

---

![image](https://user-images.githubusercontent.com/173624/170941452-0a6c24bf-58bf-4d63-9a5f-bdea1d2ebda6.png)

---

![image](https://user-images.githubusercontent.com/173624/170941543-e2b14782-770f-4418-9d15-045df756ce83.png)

---

After reading the specification, I think it would make more sense (and will be much easier to understand) to introduce a `miscellaneous` table type and don't bother the user with different definitions and classes.
Methods like `__add__` or `process_index()` can then check for the index type and raise an error or skip the table if the index is not filewise or segmented.

**Comment by frankenjoe** [comment]
> We could integrate the specifications under "Tables", but at the moment "Tables" is very much focused on filewise or segmented tables, e.g.

Why not add "Miscellaneous tables" as an own entry? 

> Methods like __add__ or process_index() can then check for the index type and raise an error or skip the table if the index is not filewise or segmented.

I'm not really in favor of that. It means we have to touch all those functions, some of them outside the package.
