### ISSUE TITLE
Always assign names to the levels of a MiscTable index

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audformat#196]
As the following examples show loading a database can fail if no names are assigned to the levels of  a `MiscTable` index:

```python
index = pd.Index([])
db = audformat.testing.create_db(minimal=True)
db['misc'] = audformat.MiscTable(index)
db.save('db')
audformat.Database.load('db')
```
```
ValueError: 'usecols' must either be list-like of all strings, all unicode, all integers or a callable.
```

Same when using a `MultiIndex` without names:

```python
index = pd.MultiIndex.from_tuples(
    [
        ('a', 0),
        ('b', 1),
        ('c', 2),
    ],
)
db['misc'] = audformat.MiscTable(index)
db.save('db')
audformat.Database.load('db')
```
```
ValueError: 'usecols' must either be list-like of all strings, all unicode, all integers or a callable.
```

The examples work when names are assigned to the levels.

I see two solutions:
1. raise an error when levels have no names
2. assign default names in that case

I think 1. is the cleaner solution.

**Comment by hagenw** [comment]
I don't see the need for enforcing levels. If you have an empty table with an emtpy index, it's fine to don't have levels.

```python
import audformat
import pandas as pd

misc_table = audformat.MiscTable(pd.Index([]))
```

If you then try to load a Misc Table without levels, I would just instanciate it with `pd.Index([])`. If this does not fit with the CSV file entries, it will then raise an error automatically.

**Comment by hagenw** [comment]
It would be strange to forbid it as the following is also allowed:

```python
table = audformat.Table(audformat.filewise_index([]))
```

**Comment by hagenw** [comment]
For the case of an non-empty index we should then indeed raise an error that level names need to be provided.

Maybe we can also add an option `levels` to `audformat.MiscTable`?

**Comment by frankenjoe** [comment]
> It would be strange to forbid it as the following is also allowed:
> 
> ```python
> table = audformat.Table(audformat.filewise_index([]))
> ```

But here we assign `file` as level name.

> If you have an empty table with an emtpy index, it's fine to don't have levels.

An empty index still has a level.

> For the case of an non-empty index we should then indeed raise an error that level names need to be provided.

Once we implement `MIscTable.extend()` you can start with an empty index and extend it later.

**Comment by hagenw** [comment]
OK, so then the question is if we should only support

```python
idx1 = pd.Index([], name='level1')
misc_table1 = audformat.MiscTable(idx1)
idx2 = pd.MultiIndex.from_tuples([], names=['level1', 'level2'])
misc_table2 = audformat.MiscTable(idx2)
```

or in addition

```python
idx1 = pd.Index([])
misc_table1 = audformat.MiscTable(idx1, levels='level1')
idx2 = pd.MultiIndex.from_tuples([])
misc_table2 = audformat.MiscTable(idx2, levels=['level1', 'level2'])
```

The second has the advantage that the user don't need to understand that `names` in `pandas` refers to `levels`.
The downside is that we now have to handle the case the `names` of the index could be different from the provided `levels`.

**Comment by frankenjoe** [comment]
> The downside is that we now have to handle the case the names of the index could be different from the provided levels.

Yes, I would not implement it that way, but instead the user should assign level names to the `index` directly.

**Comment by hagenw** [comment]
> I think 1. is the cleaner solution.

I agree with this.

**Comment by frankenjoe** [comment]
Maybe we should also show `db['misc'].get()` in the `Examples` section?

**Comment by frankenjoe** [comment]
I'm referring to this section:

![image](https://user-images.githubusercontent.com/10383417/172371568-9fd1e2a3-2256-47bf-92f7-e7936417a6d1.png)

**Comment by frankenjoe** [comment]
But I made my comment in the wrong issue, should go to: #195

**Comment by hagenw** [comment]
Ah, right. That makes sense.

I will add it to https://github.com/audeering/audformat/pull/195
