### ISSUE TITLE
Restrict input of dtype for audformat.Scheme?

### ISSUE THREAD

**Issue by hagenw** [audeering/audformat#206]
In the documentation for `audformat.Scheme` we state:

![image](https://user-images.githubusercontent.com/173624/179702675-5180a064-3f56-4b46-940d-4001f7a968c0.png)

But in the code we allow a lot more:

```python
    _dtypes = { 
        'bool': define.DataType.BOOL,
        bool: define.DataType.BOOL,
        'str': define.DataType.STRING,
        str: define.DataType.STRING,
        'int': define.DataType.INTEGER,
        int: define.DataType.INTEGER,
        'float': define.DataType.FLOAT,
        float: define.DataType.FLOAT,
        'time': define.DataType.TIME,
        pd.Timedelta: define.DataType.TIME,
        'date': define.DataType.DATE,
        datetime.datetime: define.DataType.DATE,
        pd.Timestamp: define.DataType.DATE,
    }
    dtype = self._dtypes[dtype]
```

It might be convenient to have it, but I'm wondering if we then should document it?

**Comment by frankenjoe** [comment]
I think we mainly require those additional types internally, but I don't think the user has to know about it.

**Comment by hagenw** [comment]
> I think we mainly require those additional types internally, but I don't think the user has to know about it.

No, in https://github.com/audeering/audformat/pull/204 I adjusted the code already so we don't need them. They are only needed if a user provides `float` instead of `'float'` etc.

**Comment by hagenw** [comment]
The problem is that it will break existing code as we have used the current syntax of `float` already at a lot of places in the tests, so most likely it is also used in user scripts.

**Comment by frankenjoe** [comment]
Yes, we should remove the support, but maybe we don't need to expose it in the documentation.

**Comment by hagenw** [comment]
OK, I think the main reason I opened this issue was that it is not easy in the code to understand why we have the current mapping as it is not mentioned in the docstring. So maybe we just add a comment in the code why we do the mapping and can then close this issue.
