### ISSUE TITLE
Error saving NaN for a boolean scheme

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audformat#21]
This is a minimal example with one table that has a column linked to boolean scheme:

```python
import audformat


db = audformat.testing.create_db(minimal=True)
db.schemes['scheme'] = audformat.Scheme(audformat.define.DataType.BOOL)
db['t'] = audformat.Table(audformat.filewise_index(['f1']))
db['t']['c'] = audformat.Column(scheme_id='scheme')
```

By default, the labels in the column are initialized with `NaN` and we get the following expected output:

```python
db['t'].get()
```
```
        c
file     
f1    NaN
```

However, saving and loading the database as CSV fails (using pickle works):

```python
db.save('db')
audformat.Database.load('db')
```
```
ValueError: Bool column has NA values in column 1
```

There are two solutions:

1. we do not support `NaN` for boolean schemes and initalize with `False`
2. we try to find a fix for loading empty values to a boolean scheme from CSV

**Comment by hagenw** [comment]
I would vote for allowing to store `NaN` as it can simply indicate that you haven't got a response for a given entry. And there might be questions were there is no good default answer (like `False`).

**Comment by frankenjoe** [comment]
Agree, I also think we should support `NaN`. I will try to find a fix using solution 2. then.

**Comment by frankenjoe** [comment]
Cool, just found out that `pandas` actually has a type for nullable bool values: https://pandas.pydata.org/pandas-docs/stable/user_guide/boolean.html. This will be very helpful to fix the issue :)
