### ISSUE TITLE
Support for pd.StringDType

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audformat#210]
In 1.3 Pandas has introduced [pd.StringDType](https://pandas.pydata.org/docs/reference/api/pandas.StringDtype.html) as dtype for string data. It's still experimental, but could be very useful in the context of annotation where we usually have short and repeating strings:

![image](https://user-images.githubusercontent.com/10383417/179995563-beebe946-ffd7-4883-91ce-2a7494dbdad9.png)

and also in the [documentation](https://pandas.pydata.org/docs/user_guide/text.html) they already suggest to use it:

![image](https://user-images.githubusercontent.com/10383417/179995770-7c36bfd0-8069-4a83-986b-c7e1e727e793.png)

Though it's still marked as experimental features we can expect that it will become the standard to store string data int the future and think about ways to support it.

**Comment by hagenw** [comment]
If `pandas` does not make it the default when doing something like `pd.Series(['a'])` or `pd.Index(['a'])`, we would need to check in those cases for the dtype ourselves and set it to `string`.

**Comment by frankenjoe** [comment]
Not necessarily, if the user does not set `dtype=string`. it would be handled as `object` just as it is now. But we should at least add support for `pd.StringDtype` if the user explicitly sets it (and this way tells us that the data actually contains only strings and not something else). It would also help us to solve issues as described in #211.
