### ISSUE TITLE
Add define.DataType.Object

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audformat#211]
As mentioned in https://github.com/audeering/audformat/pull/204#issuecomment-1190276787 with `MiscTable` we currently map levels with type `object` (which might contain strings or something else) always to our internal type `define.DataType.String`, which can lead to the following situation:

```python
db = audformat.testing.create_db(minimal=True)
index = pd.Index([[0, 0], [1, 1]], name='list')
audformat.MiscTable(index)
```
```
levels: {list: str}
```

As noted in #210 there is now a string type in Pandas that would allow us to differentiate between levels that contain string or generic object data. So maybe we should introduce `define.DataType.Object` and in the example above output:

```
levels: {list: object}
```

We would then only show `{list: str}` if the level is explicitly set to `dtype=string`.

**Comment by hagenw** [comment]
There is one problem when implementing this: `pandas` is not able to preserve the original type in CSV and in order to convert it to the right type, we would need to store this besides `object`, e.g.

```python
df = pd.DataFrame([], columns=['data'], index=pd.Index([0], name='idx'))
df.loc[0]['data'] = [0, 1]
df.to_csv('data.csv')
df_new = pd.read_csv(
    'data.csv',
    usecols=['idx', 'data'],
    dtype={'idx': 'Int64', 'data': 'object'},
    index_col=['idx'],
)
```
and then
```python
>>> type(df.iloc[0]['data'])
list
>>> type(df_new.iloc[0]['data'])
str
```

**Comment by frankenjoe** [comment]
But aren't we already storing everything that is not linked to a scheme as `object` anyway?

**Comment by hagenw** [comment]
> But aren't we already storing everything that is not linked to a scheme as `object` anyway?

Yes, but we group it under the dtype `string` as everything is converted to string when loading from CSV anyway.
But the idea of this issue was that we separate `string` and `object` and preserve the original type (here `list`) when loading an `object`.

**Comment by frankenjoe** [comment]
Mhh, I cannot really follow you. This is how I see it:

1. store and load every column that is not assigned to a scheme as `object` (as we do already)
2. store and load columns that are assigned to a `DataType.String` scheme with `dtype=string` - for backward compatibility we possibly have to convert to `dtype=string` when loading such a column from a pickle file
3. only store levels of a `MiscTable.index` as `DataType.String` if the user sets `dtype=string`, otherwise use `DataType.Object`

**Comment by hagenw** [comment]
OK, so the main motivation is not adding support for all kind of types with `object`, but just to speed up loading strings from CSV file. This also makes sense.

**Comment by frankenjoe** [comment]
Well, we already support all kind of types, but we currently show `'str'` in that case and I think it's better to show `'object'` in that case and `'str'` only if we really know that the data contains strings and not something else - which is now possible thanks to  `pd.StringDType`. I think it's also good to do that before we release a first version with `MiscTable` to not have compatibility issues later on. The good thing with `Scheme` is that we never allowed arbitrary objects, so here we only have to make sure that we now store with `dtype='strings'` instead of `dtype='object'` when a column is assigned to `DataType.String` (I hope there is not something I ovelooked :)
