### ISSUE TITLE
Keep special treatment of filewise and segmented index objects in uils.intersect()?

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audformat#236]
In https://github.com/audeering/audformat/pull/229 we started a discussion on the current behavior of `utils.interact()` if a mixture of filewise and segmented index objects are passed. Currently one can do the following:

```python
objs = [
    audformat.filewise_index(['f1']),
    audformat.segmented_index(['f1', 'f1'], [0, 1], [1, 2]),
]
audformat.utils.intersect(objs)
```
```
MultiIndex([('f1', '0 days 00:00:00', '0 days 00:00:01'),
            ('f1', '0 days 00:00:01', '0 days 00:00:02')],
           names=['file', 'start', 'end'])
```

Here the filewise index works as kind of a filter that selects all segments from `'f1'` without adding the whole file.

### Shortcomings

The behavior is hard to predict e.g.:

```python
objs = [
    audformat.filewise_index(['f1', 'f2']),
    audformat.segmented_index(['f1', 'f2'], [0, 1], [1, 2]),
]
audformat.utils.intersect(objs)
```
```
MultiIndex([('f1', '0 days 00:00:00', '0 days 00:00:01'),
            ('f2', '0 days 00:00:01', '0 days 00:00:02')],
           names=['file', 'start', 'end'])
```

but:

```python
objs = [
    audformat.filewise_index(['f1', 'f2']),
    audformat.segmented_index(['f1', 'f1'], [0, 1], [1, 2]),
    audformat.segmented_index(['f2', 'f2'], [0, 1], [1, 2]),
]
audformat.utils.intersect(objs)
```
```
MultiIndex([], names=['file', 'start', 'end'])
```

or

```python
objs = [
    audformat.filewise_index(['f1']),
    audformat.filewise_index(['f2']),
    audformat.segmented_index(['f1', 'f2'], [0, 1], [1, 2]),
]
audformat.utils.intersect(objs)
```
```
MultiIndex([], names=['file', 'start', 'end'])
```

When filewise and segment index objects are mixed the following rule no longer applies: `(A ∩ B) ∩ C` = `A ∩ (B ∩ C)`. This is because the intersection of a filewise and a segmented index is a segmented index. And no special rule is applied when combining two segmented index objects, e.g.:

```python
objs = [
    audformat.filewise_index(['f1']),
    audformat.segmented_index(['f1', 'f1'], [0, 1], [1, 2]),
]
audformat.utils.intersect(objs)
```
```
MultiIndex([('f1', '0 days 00:00:00', '0 days 00:00:01'),
            ('f1', '0 days 00:00:01', '0 days 00:00:02')],
           names=['file', 'start', 'end'])
```

but:

```python
objs = [
    audformat.segmented_index(['f1']),
    audformat.segmented_index(['f1', 'f1'], [0, 1], [1, 2]),
]
audformat.utils.intersect(objs)
```
```
MultiIndex([], names=['file', 'start', 'end'])
```

### Proposal

Instead i suggest to implement it in the same we do with `union()`, i.e. if a mixture of filewise and segmented index objects is passed, we convert the filewise objects to segmented objects. I.e. for

```python
objs = [
    audformat.filewise_index(['f1']),
    audformat.segmented_index(['f1', 'f1'], [0, 1], [1, 2]),
]
```

we get the same result as for:

```python
objs = [
    audformat.segmented_index(['f1']),
    audformat.segmented_index(['f1', 'f1'], [0, 1], [1, 2]),
]
```

### Compatibility

Of course this would be a breaking change. However, we don't rely on this behavior inside `audformat` yet. In `Table.pick_index()` we do not allow to pass a filewise index when the table is segmented or vice versa. Instead, we offer `Table.pick_files()` to pick all segments that belong specific files, but it's not implemented using `utils.intersect()`. Outside of `audformat` we don't use `utils.intersect()` in any of our packages and it's unlikely users rely on it since - except for a docstring example - there is no documentation on this special behavior.

**Comment by hagenw** [comment]
What is missing in the proposal is the desired result.
If we implement like we do in `union()` both examples under Proposal would return an empty index.

**Comment by hagenw** [comment]
Good to hear that we are more or less free to change this to whatever we want as it is not really used/needed at the moment.

Would your proposal also solve the `union([intersect(objs), symmetric_difference(objs)])` problem discussed in https://github.com/audeering/audformat/pull/229#issuecomment-1196366003?

**Comment by frankenjoe** [comment]
> Would your proposal also solve the `union([intersect(objs), symmetric_difference(objs)])` problem discussed in [#229 (comment)](https://github.com/audeering/audformat/pull/229#issuecomment-1196366003)?

Yes, if we also simply convert filewise index to segmented index object `(A Δ B) Δ C = A Δ (B Δ C)` should work, too.

**Comment by frankenjoe** [comment]
> What is missing in the proposal is the desired result.
> If we implement like we do in `union()` both examples under Proposal would return an empty MultiIndex.

But that is the expected result :)

Here's an example where the result would be not empty:

```
objs = [
    audformat.filewise_index(['f1']),
    audformat.segmented_index(['f1', 'f1'], [0, 1], [pd.NaT, 2]),
]
audformat.utils.intersect(objs)
```
```
MultiIndex([('f1', '0 days', NaT)],
           names=['file', 'start', 'end'])
```

**Comment by hagenw** [comment]
OK, your proposal makes sense.

For the current behavior when using a mixture of filewise and segmented, `intersect()` is not really needed as a user could simply use `isin()` to get the desired result.
