### ISSUE TITLE
What should interesect() return for single index?

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audformat#238]
If we pass a single index object to `utils.intersect()` we currently return that index:

```python
objs = [audformat.filewise_index(['f1', 'f2'])]
audformat.utils.intersect(objs)
```
```
Index(['f1', 'f2'], dtype='string', name='file')
```

But wouldn't it make more sense to return an empty index?

**Comment by hagenw** [comment]
Good question.
We have:
A ∩ A = A
and
A ∩ Ø = Ø

As we pass a list of objects, this most likely would mean:

```python
audformat.utils.intersect([index])
```
should return an empty index
and
```python
audformat.utils.intersect([index, index])
```
should return `index`.

So, yes, we should change the current behavior.
