### ISSUE TITLE
Should utils.union() be commutative?

### ISSUE THREAD

**Issue by hagenw** [audeering/audformat#240]
At the moment the result of `audformat.utils.union(objs)` depends on the order of objects.
E.g.

```python
>>> audformat.utils.union([audformat.filewise_index(['f1']), audformat.filewise_index(['f2'])])
Index(['f1', 'f2'], dtype='string', name='file')
```

```python
>>> audformat.utils.union([audformat.filewise_index(['f2']), audformat.filewise_index(['f1'])])
Index(['f2', 'f1'], dtype='string', name='file')
```

You could call this a feature, but on the other hand in set theory it is usually assumed that `union` is a commutative operation.

**Comment by frankenjoe** [comment]
Yes, I'm facing the same issue with the new implementation of `symmetric_difference()` that I'm preparing. In order to make the permutation tests work I have to sort the result.

**Comment by frankenjoe** [comment]
So the question is should we always sort the result? But this will add some extra costs to the function and in most cases the order will probably not matter.

**Comment by hagenw** [comment]
The question is if there is another way without relying on sort.

**Comment by frankenjoe** [comment]
I first sort ordering by length might help, but then we still have the problem with index objects of same length.

**Comment by frankenjoe** [comment]
We could order by length and if objects have the same length use the hash?

**Comment by hagenw** [comment]
Yes, but I think we should make it an optional argument and set it to `False` as default as this removes also a feature.

One usage of `union()` is like `concat()`, but for indices, that means users might want to have an influence on the order by the order of provided objects.

**Comment by frankenjoe** [comment]
Yes, I would also not sort by default. The question is if we really need an argument, as the user can simply do: `union(objs).sort_level()[0]`

**Comment by frankenjoe** [comment]
Or we add an argument `communicative` that does not sort by value, but in some other way (e.g. length + hash) to ensure the operation is communicative if that is important to the user.
