### ISSUE TITLE
Speedup intersect() and symmetric_difference() by using set

### ISSUE THREAD

**Issue by hagenw** [audeering/audformat#245]
See the discussion at https://github.com/audeering/audformat/pull/241#discussion_r932147625.

Both functions could be speed up by using `set()`, e.g.

```python
    index = set()
    for obj in objs:
        index = index.symmetric_difference(set(obj))
    index = tuple(index)

    if isinstance(obj, pd.MultiIndex):
        index = pd.MultiIndex.from_tuples(index, names=obj.names)
        index = set_index_dtypes(index, dict(obj.dtypes))
    else:
        index = pd.Index(index, name=obj.name, dtype=obj.dtype)
```

**Comment by frankenjoe** [comment]
So the main concern would be that we don't have control over the order, correct?

**Comment by hagenw** [comment]
I'm not yet completely sure if the order is deterministic.

But you can add `sort()` to the test cases.

**Comment by frankenjoe** [comment]
I'm more concerned about the consequences this has if we rely e.g. on `intersect()` in `Table.pick_index()`. E.g if the index of the table is `f1, f2, f3`, then you pick `f1, f2` the index of the result might be `f2, f1`.

**Comment by hagenw** [comment]
Yes, we should add tests to make sure that this doe snot happen.
If we would need to sort the index to avoid this, then I think the speedup we would get is not worth the effort.
