### ISSUE TITLE
Add testing.add_misc_table()

### ISSUE THREAD

**Issue by hagenw** [audeering/audformat#260]
It would be a good idea to add `testing.add_misc_table()` or expand `testing.add_table()` as discussed in https://github.com/audeering/audformat/pull/255#discussion_r934238298

**Comment by frankenjoe** [comment]
I would suggest we add `testing.add_misc_table()` since `testing.add_table()` has several arguments (e.g. `num_files`) that are specific to `audformat' tables and make no sense for `MiscTable` objects.
