### ISSUE TITLE
Add type hint string to arguments that expect values from define.* classes

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audformat#269]
See e.g. the `dtype` argument in `Scheme`:

![image](https://user-images.githubusercontent.com/10383417/182593245-2bb08d3b-9eb3-418d-8624-9bd5e772b287.png)

The type hint does not include string, even though we even list strings as supported values in the docstring. I sugget we add `string` here and other places where the argument expects a value from `audformat.define.*`.

**Comment by hagenw** [comment]
It also has a bug at the moment as `audformat.define.DataType` is not a type, is it.
So maybe simply replace it with `str`.

**Comment by frankenjoe** [comment]
I think you are right, but it has the advantage that it links to the class where the values are defined. If we remove it we have to manually add a link in the description of the argument. So maybe we should keep it?

**Comment by hagenw** [comment]
We have already a link to the class in the description.
