### ISSUE TITLE
Where to store license of a database?

### ISSUE THREAD

**Issue by hagenw** [audeering/audformat#27]
We don't have any `db.license` entry at the moment. Before it was handled inside the Gradle settings, but I think we should add an option to store it also in the database.
Of course, it can be done already by using the `meta` field or adding it to the description, but I think we should add an extra entry for it.

Some licenses might come with an URL, so maybe we should add such an option as well.

**Comment by frankenjoe** [comment]
Actually, in an early version of `audata` we had a license field, but then decided to remove it and handle it with `Gradle` :) But yes, I would say it's an important piece of information that should be part of the header.

What about the list of maintainers?

**Comment by hagenw** [comment]
> What about the list of maintainers?

Good point, I think it makes sense to put this into the database as well.

**Comment by hagenw** [comment]
>> What about the list of maintainers?
>
> Good point, I think it makes sense to put this into the database as well.

I think I changed my mind and would not include `maintainers` in the database, but we might want to add `author` instead?

**Comment by frankenjoe** [comment]
Fine for me, too.

**Comment by frankenjoe** [comment]
Closing as we now have `license` (see https://github.com/audeering/audformat/pull/34) and `author` (see https://github.com/audeering/audformat/pull/40) fields.
