### ISSUE TITLE
to_filewise_index doens't accept MultiIndex

### ISSUE THREAD

**Issue by felixbur** [audeering/audformat#281]
here's my code:
type(seg_index)
pandas.core.indexes.multi.MultiIndex
to_filewise_index(seg_index, root, 'audio_out', progress_bar = True)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-1b24d3f316de> in <module>
----> 1 to_filewise_index(seg_index, root, 'audio_out', progress_bar = True)

~/tmp/Python-Wrapper-for-World-Vocoder/venv/lib/python3.6/site-packages/audformat/core/utils.py in to_filewise_index(obj, root, output_folder, num_workers, progress_bar)
    962         return obj
    963 
--> 964     test_path = obj.index.get_level_values(define.IndexField.FILE)[0]
    965     is_abs = os.path.isabs(test_path)
    966     test_path = audeer.path(test_path)

AttributeError: 'MultiIndex' object has no attribute 'index

**Comment by frankenjoe** [comment]
Thanks for reporting, we indeed do not check first if the input is an index or a series / frame. As a workaround, you can try:

```python
to_filewise_index(pd.Series(index=seg_index), root, 'audio_out', progress_bar = True)
```

**Comment by hagenw** [comment]
I mark it as a bug as the documentation states we accept indices as input.

**Comment by hagenw** [comment]
@felixbur reported that `pd.Series` does also not work, he had to use `pd.DataFrame` instead.

**Comment by felixbur** [comment]
>to_filewise_index(pd.Series(index=seg_index), 

Series also doesn't work but

to_filewise_index(pd.DataFrame(index=seg_index), 

is a workaround
