### ISSUE TITLE
Documentation for Scheme.labels indicates wrongly that it returns a list

### ISSUE THREAD

**Issue by hagenw** [audeering/audformat#283]
See

![image](https://user-images.githubusercontent.com/173624/183834635-c4f13276-ba25-4b9e-a733-851968a64111.png)

but it might also return a dictionary or a string.

**Comment by frankenjoe** [comment]
Or can be `None`.

**Comment by frankenjoe** [comment]
@hagenw would you like to fix this before we do a new release?

**Comment by hagenw** [comment]
Yes, I will create a pull request for this. Could you maybe take a look at https://github.com/audeering/audformat/issues/281, this should be also straightforward.
