### ISSUE TITLE
Add option inplace to expand_file_path() and map_file_path()?

### ISSUE THREAD

**Issue by hagenw** [audeering/audformat#287]
If you want to change an index of a table with one of those utility functions, the only way to achieve this is by:

```python
index = audformat.utils.map_file_path(table.index, mapping)
table._df.index = index
```

which is not how a user is supposed to interact with the tables.
So, it would made sense to add an option `inplace` to those functions to allow changing the index directly in the table:

```python
audformat.utils.map_file_path(table.index, mapping, inplace=True)
```

**Comment by frankenjoe** [comment]
But that means we have to pass the `Table` object to the function.

**Comment by frankenjoe** [comment]
The method we currently have for this use case is `Database.map_files()`, but it applies it to all tables of course.

**Comment by hagenw** [comment]
An alternative to `inplace` would be to add a method to `audformat.Table` that allows to replace the index (instead of only extending it).

**Comment by frankenjoe** [comment]
Or we add `Table.map_files()` that works like `Database.map_files()` on one table?

**Comment by hagenw** [comment]
If this is able to replace the usage of the two utility functions (`replace_file_extension()` is another one) at

https://github.com/audeering/audb/blob/v1.3.0/audb/core/load.py#L631-L647

then it might be a solution.

**Comment by frankenjoe** [comment]
`map_files()` takes a function as input, so I guess you can do whatever you like with the file names.
