### ISSUE TITLE
Table.drop_index() may extend the index

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audformat#290]
Segments or files that are not in the table will be added.

```python
db = audformat.testing.create_db(minimal=True)
db['table'] = audformat.Table(audformat.filewise_index(['f1', 'f2']))
db['table'].drop_index(audformat.filewise_index(['f2', 'f3']), inplace=True)
db['table'].index
```
```
Index(['f1', 'f3'], dtype='string', name='file')
```

expected:

```
Index(['f1'], dtype='string', name='file')
```

**Comment by hagenw** [comment]
The problem is we just take the difference between the two indices:

https://github.com/audeering/audformat/blob/master/audformat/core/table.py#L319

**Comment by frankenjoe** [comment]
Yes, we need to remove the intersection instead. And we need to add better tests!
