### ISSUE TITLE
If HeaderDict.sorted_iter is True should we also return keys() and values() alphabetically sorted?

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audformat#296]
We have a `sorted_iter` argument in `HeaderDict` to control if items should be returned  alphabetically ordered. Currently, it only affects `.items()`, but not `.keys()` and `.values()`. E.g.:

```python
db = audformat.testing.create_db(minimal=True)
db.schemes['b'] = audformat.Scheme()
db.schemes['a'] = audformat.Scheme()
[(key, value) for key, value in db.schemes.items()]
```
```
[('a', {dtype: str}), ('b', {dtype: str})]
```

But:

```python
[(key, value) for key, value in zip(db.schemes.keys(), db.schemes.values())]
```
```
[('b', {dtype: str}), ('a', {dtype: str})]
```

And when a database is stored to disk, `items()` is used, i.e. after loading the database we get:

```python
db.save('db')
db = audformat.Database.load('db')
[(key, value) for key, value in zip(db.schemes.keys(), db.schemes.values())]
```
```
[('a', {dtype: str}), ('b', {dtype: str})]
```

So the question is if it makes more sense to also return `keys()` and `values()` alphabetically ordered.

**Comment by hagenw** [comment]
The current implementation seems only to affect the presentation to the user, not how it is stored:

```python
import audformat.testing
db = audformat.testing.create_db(minimal=True)
db.schemes['b'] = audformat.Scheme()
db.schemes['a'] = audformat.Scheme()
```
then you get
```python
>>> list(db.schemes)
['b', 'a']
>>> db.schemes.popitem()
('a', {dtype: str})
>>> list(db.schemes)
['b']
```
which totally makes sense to me, but would be strange if `list(db.schemes)` would have returned the list in aplhabetically order.

**Comment by frankenjoe** [comment]
> hich totally makes sense to me, but would be strange if list(db.schemes) would have returned the list in alphabetical order.

But after loading from disk it does...

**Comment by hagenw** [comment]
> > hich totally makes sense to me, but would be strange if list(db.schemes) would have returned the list in alphabetical order.
> 
> But after loading from disk it does...

Yes, but there the order of schemes is not given by the user. There might be the case that you as user create the `db` object save it to disk and load it again. Then you might wonder that the order has changed, but in my opinion this is ok. An alternative would be to always return the entries in the order they were created, but I think this will harm usability of when dealing with databases by loading them with `audb` as it is easier to grasp an alphabetically ordered list for databases where you were not involved in creating them.

**Comment by frankenjoe** [comment]
As a user I would not expect that `.items()` sometimes returns a different order than `.keys()` and `.values()`. But ok, if you think it makes more sense the way it is, I'm fine with keeping this behavior.

**Comment by hagenw** [comment]
I have not really talked about `items()`, `keys()` and `values()`. I only said that `list(db.schemes)` and `db.schemes.popitem()` should work as they do at the moment. If you can adjust `keys()` and `values()` to `items()` without affecting the current behavior of what I described you can do it.

**Comment by frankenjoe** [comment]
Exactly, we are only talking about '.keys()` and `values()` here and if they should return the same order as `items()`.
