### ISSUE TITLE
Add helper function to access labels from Scheme

### ISSUE THREAD

**Issue by hagenw** [audeering/audformat#301]
At the moment we have `Scheme.labels`, which is an attribute and has to contain a string value when a misc table is used as scheme.
This means there is no direct way to access the labels of this scheme.
Internally we have `Scheme._labels_to_list()` and `Scheme._labels_to_dict()`. Maybe we could create a single public method to access the labels in a desired fromat.

**Comment by frankenjoe** [comment]
Yes, I think that would be useful.

**Comment by hagenw** [comment]
One way could be to use `list`, e.g. `list(db.schemes[scheme_id])`

**Comment by frankenjoe** [comment]
I agree it looks elegant, but maybe something like `Scheme.labels_as_list` is easier to find for a user?

**Comment by hagenw** [comment]
Yes, the problem with `list()` is indeed that it is very hard to find in the documentation or by using tab autocompletion on the scheme object.
