### ISSUE TITLE
Add support for misc table in audformat.Rater

### ISSUE THREAD

**Issue by hagenw** [audeering/audformat#302]
To store large metadata (labels) for schemes we now support using misc tables, which will store the metadata in a CSV file.
Some large amount of metadata might also come with the raters that are part of a database. They are usually stored with the `audformat.Rater` object, which can contain a dictionary to hold those metadata.

I think it would make sense to also support the usage of a misc table to store those metadata for rater as we did for schemes.

**Comment by frankenjoe** [comment]
Yes, that would be a useful extension.

**Comment by hagenw** [comment]
The question is if we then should add a `labels` argument to `audformat.Rater` or should use the `meta` argument instead which is used at the moment. I'm not too much in favor of using `meta` and expect a misc table if a string value is given, but would expect to use `meta` as you can do with all other `audformat` objects like `Scheme`.

If we introduce `labels` it would break backward compatibility, but only on a semantic level, not on the code level as all the old `meta` information about raters is still loaded. The biggest problem that might occur is that you update/combine two databases that store the raters labels differently, and in the end you have that information spread to `meta` and `labels`.

**Comment by frankenjoe** [comment]
> The question is if we then should add a labels argument to audformat.Rater

I guess that makes most sense

> and in the end you have that information spread to meta and labels

maybe we raise an error if a user tries to combine raters that have `meta` and `labels`?

**Comment by hagenw** [comment]
> > and in the end you have that information spread to meta and labels
> 
> maybe we raise an error if a user tries to combine raters that have `meta` and `labels` set?

Not sure if this is really needed, but it might be an option. Of cause, we have to check that `meta` really contains labels when raising the error and not other valid metadata entries.

**Comment by hagenw** [comment]
Adding a `labels` argument to `audformat.Rater` makes not much sense as we have one object per rater.
Hence, I would propose we don't change anything with the underlying behavior of `audformat.Rater`, but propose that additional information on the raters should not be stored under `meta`, but simply added as a misc table. This could lead to some inconsistencies when maintained manually, but when exporting from rating platforms in an automatic manner, I don't see any issues with it.

**Comment by frankenjoe** [comment]
@hagenw since we came to the conclusion that we will not add support for misc tables with raters, I propose we either close the issue or if we plan to extend the documentation change the title and label.

**Comment by hagenw** [comment]
We can close here.
