### ISSUE TITLE
Avoid pandas warning

### ISSUE THREAD

**Issue by hagenw** [audeering/audformat#319]
At the moment we are getting:

```
.../audformat/core/column.py:340: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace ins
tead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`                              
  df.loc[index, column_id] = pd.Series(     
```

The affected code is:

```python
            df.loc[index, column_id] = pd.Series(
                values,
                index=index,
                dtype=dtype,
            )
```

As usual we cannot directly use the suggestions of `pandas` to change the code.

**Comment by frankenjoe** [comment]
To me it sounds ok that values are changed inplace. Not sure if we need to address this warning.

**Comment by hagenw** [comment]
I still don't get the warning. If I read the explanation given at https://pandas.pydata.org/docs/dev/whatsnew/v1.5.0.html#inplace-operation-when-setting-values-with-loc-and-iloc it sounds like the warning should only occur if the `dtype` of the original column and the series we assign would not match. So maybe we should double check if this is the case?

**Comment by frankenjoe** [comment]
Mhh, I'm also seeing the warning when I change to:

```
            df.loc[index, column_id] = pd.Series(
                values,
                index=index,
                dtype=df[column_id].dtype,
            )
```

**Comment by hagenw** [comment]
They state at https://github.com/pandas-dev/pandas/issues/47381#issuecomment-1158023223 that using the same dtype should not result in getting the warning.
So maybe it's a bug in `pandas`?
