### ISSUE TITLE
Forbid duplicated index entries?

### ISSUE THREAD

**Issue by hagenw** [audeering/audformat#32]
As some methods like `audformat.Table.drop_files()` will fail if the database contains duplicated index entries, we should maybe forbid this in the first place.

The question is if we can find a good place to do this. The first places that come to mind are `Column.set()` and maybe `Database.save()`. I guess, this will still not completely safe as you can also directly assign the dataframe, but maybe this is then not a bug, but a feature for the power user.

**Comment by frankenjoe** [comment]
I think we should add it in three places:

* `audformat.segmented_index()`
* `audformat.filewise_index()`
* `audformat.Table()`

And we should also check how `audformat.Table.extend()` behaves.

In `Column.set()` you cannot add new segments/files, but only set values to the existing index.

**Comment by hagenw** [comment]
BTW, there would be a way to support duplicated index entries in `drop_files`:

We need to check if we have a filewise index or a segmented and for a segmented index we should do:
```python
self._df.drop(index, level='file', inplace=True)
```
instead of
```python
self._df.drop(index, inplace=True)
```
And maybe use a list of files instead of an index.

**Comment by frankenjoe** [comment]
Ok, but do we want to support duplicated entries?

I'd say no. E.g. if we have:

``` python
table = Table(audformat.filewise_index('f1', 'f1', 'f1'))
```

and later we use:

``` python
table.set(value, index=audformat.filewise_index('f1')
```

should we assign the value to the first, second, or third entry or all of them? And what about this case:

``` python
table.set([value] * 2, index=audformat.filewise_index(['f1', 'f1'])
```

Same problem with `get`:

``` python
table.get(audformat.filewise_index(['f1'])  # ?
table.get(audformat.filewise_index(['f1', 'f1'])   # ?
```

And I guess more problems like this will pop up...

**Comment by hagenw** [comment]
I agree, we should not support it.

I just wanted to mention how you could still use `drop_files()` if you have a dataframe that has already dplicated entries.

**Comment by frankenjoe** [comment]
OK!

So I suggest to create a helper function that checks for duplicated entries in the index and raises an error. Then we can call this function in various places where we need to ensure a unique index. Makes sense?
