### ISSUE TITLE
Speedup by specifying dtype for index columns when reading CSV files

### ISSUE THREAD

**Issue by hagenw** [audeering/audformat#33]
Reading CSV files with `pandas.read_csv()` is faster if you provide data types of the columns, e.g. https://towardsdatascience.com/️-load-the-same-csv-file-10x-times-faster-and-with-10x-less-memory-️-e93b485086c7

At the moment we [specify data types for all the data columns](https://github.com/audeering/audformat/blob/de6073060de76d3d413baff30455c8cd0fbf6b13/audformat/core/table.py#L882-L894),
but [not for the index columns](https://github.com/audeering/audformat/blob/de6073060de76d3d413baff30455c8cd0fbf6b13/audformat/core/table.py#L867-L876).

I'm also wondering  if `dtype = schemes[column.scheme_id].to_pandas_dtype()` is sufficient to detect [categorical](https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html) data types instead of strings.

**Comment by frankenjoe** [comment]
> At the moment we specify data types for all the data columns,
but not for the index columns.

Very good observation!

> I'm also wondering if dtype = schemes[column.scheme_id].to_pandas_dtype() is sufficient to detect categorical data types instead of strings.

Mhh, I guess we should give it a try. Would simplify the code quite a lot I think.

**Comment by hagenw** [comment]
>> I'm also wondering if dtype = schemes[column.scheme_id].to_pandas_dtype() is sufficient to detect categorical data types instead of strings.

> Mhh, I guess we should give it a try. Would simplify the code quite a lot I think.

We are [using it already](https://github.com/audeering/audformat/blob/de6073060de76d3d413baff30455c8cd0fbf6b13/audformat/core/table.py#L885). I'm more worried that it is not sufficient and that loading takes longer / needs more RAM then.

**Comment by frankenjoe** [comment]
Ah sorry, misunderstood.

**Comment by frankenjoe** [comment]
> We are using it already. I'm more worried that it is not sufficient

so you are afraid that it will not keep the correct categories? E.g. if some class is not represented?

**Comment by hagenw** [comment]
No I'm afraid that it does not detect that the data type is categorical, but that it just detects that the data type is string.

I couldn't find documentation on how `to_pandas_dtype()` works exactly.

**Comment by frankenjoe** [comment]
If it would change the `dtype` our tests should fail. So I think we are safe here, but it might fail if not all classes are represented in the according CSV column. I am not sure if we have a test for that.

> I couldn't find documentation on how to_pandas_dtype() works exactly.

https://audeering.github.io/audformat/api.html#audformat.Scheme.to_pandas_dtype

**Comment by hagenw** [comment]
The discussion regarding `to_pandas_dtype()` we can skip as I don't see any issue with its current implementation.

Instead we should focus and testing if we can speed up CSV loading by specifying `dtype` for the `file` column, which is the only setting missing. As reading strings will most likely be slow anyway, I don't expect a performance boost, but at least we can test.
