### ISSUE TITLE
DOC: class appears twice in TOC

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audformat#341]
![image](https://user-images.githubusercontent.com/10383417/211650027-d8f0a0db-4a0d-4338-bb06-e9e59c3ea27b.png)

is this expected?

**Comment by hagenw** [comment]
No, this is an old issue, see https://github.com/audeering/audinterface/pull/80

We have solved it here in https://github.com/audeering/audformat/pull/325

**Comment by frankenjoe** [comment]
Yes, that's what I thought, too. I thought we had already applied the fix here, too :)

**Comment by hagenw** [comment]
We had, but we didn't do a new release yet as we first wanted to prepare `audb` to work with `audformat.Attachment` (which I'm doing at the moment), see also https://github.com/audeering/audformat/pull/333

**Comment by frankenjoe** [comment]
Ok, great.
