### ISSUE TITLE
audformat.utils.expand_file_path() might expand the provided root argument

### ISSUE THREAD

**Issue by hagenw** [audeering/audformat#371]
In `audformat.utils.expand_file_path()` we state:

![image](https://user-images.githubusercontent.com/173624/232011916-b920c1c5-72ba-4a92-9f89-b946686ab530.png)

And provide the following example:

```python
>>> index = audformat.filewise_index(['f1', 'f2'])
>>> audformat.utils.expand_file_path(index, '/some/where')
Index(['/some/where/f1', '/some/where/f2'], dtype='string', name='file')
```

What is not documented is the behavior if `root` is not ab absolute dir.
I would expect that it would raise an error stating that `root` is not an absolute dir or bahve in the following way:
```python
>>> audformat.utils.expand_file_path(index, 'some/where')
Index(['some/where/f1', 'some/where/f2'], dtype='string', name='file')
```

What it does instead is:
```python
>>> audformat.utils.expand_file_path(index, 'some/where')
Index(['/home/audeering.local/hwierstorf/git/audeering/audformat/some/where/f1', '/home/audeering.local/hwierstorf/git/audeering/audformat/some/where/f2'], dtype='string', name='file')
```

I would consider this a bug.

**Comment by frankenjoe** [comment]
You are right, the current behavior is strange and we should change it. At the moment I don't see that anything speaks against expanding with a relative path.
