### ISSUE TITLE
Request table by index with additional files

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audformat#42]
Currently, this is not working:

```python
db = audformat.testing.create_db(minimal=True)
db.schemes['int'] = audformat.Scheme(int)
audformat.testing.add_table(
    db,
    'files',
    'filewise',
    num_files=[0, 1],
)
print(db['files'].get())
audformat.testing.add_table(
    db,
    'segments',
    'segmented',
    num_files=[1, 2],
)
print(db['segments'].get())
df = db['files'].get(index=db['segments'].index)
print(df)
```
```
               int
file              
audio/000.wav   42
audio/001.wav   33
                                                                   int
file          start                     end                           
audio/001.wav 0 days 00:00:00.112525598 0 days 00:00:00.651033666   29
              0 days 00:00:00.774044425 0 days 00:00:01.252506888   53
              0 days 00:00:02.059782689 0 days 00:00:02.436929941   91
              0 days 00:00:02.506858415 0 days 00:00:02.967737843   97
              0 days 00:00:03.548951851 0 days 00:00:04.280189899   40
audio/002.wav 0 days 00:00:01.050809893 0 days 00:00:01.472755921   70
              0 days 00:00:01.583978939 0 days 00:00:01.859228829   82
              0 days 00:00:02.071727758 0 days 00:00:03.610085480   97
              0 days 00:00:03.890518902 0 days 00:00:03.916600049   67
              0 days 00:00:04.290822547 0 days 00:00:04.882961055   20
Traceback (most recent call last):
...
    "Passing list-likes to .loc or [] with any missing labels "
KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Index(['audio/002.wav', 'audio/002.wav', 'audio/002.wav', 'audio/002.wav',\n       'audio/002.wav'],\n      dtype='object', name='file'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"
```

As we can see, pandas is complaining that `db['segments'].index` has a reference to a file ` 'audio/002.wav'` that is not in `db['files']`.

Question: should we add support for this case? And if so, how should we handle it? Just Ignore those files?

cc @hagenw

**Comment by frankenjoe** [comment]
Btw: we get the same error if request with a filewise index and also if the table is segmented.

**Comment by hagenw** [comment]
I would it's fine if we get an error in the case that the index contains additional files.

**Comment by frankenjoe** [comment]
The problem popped up in one of our benchmarks:

https://gitlab.audeering.com/project/audeo/modelling/benchmark/-/issues/7

So basically we may have the following use-case:

1. we have a table `segments` holding all segments of a database
2. we have several tables holding filewise annotations but not necessarily referencing all files in the database

In that case we cannot use the index of `segments` to request data from the filewise tables.

**Comment by ATriantafyllopoulos** [comment]
> I would say it's fine if we get an error in the case that the index contains additional files.
> 
> Or did you had a particular usecase in mind where this might be needed?

As I created the dataset like this, let me explain my reasoning.

+ We have a `filewise` dataset, where we know the speakerID and language for each file
+ We want to do language identification using speaker-independent splits
+ We (might) want to do speaker identification using speaker-dependent splits

Therefore, we might have 2 (or in general more) different train/dev/test splits for several tasks. So far, for the dataset in question, we have created just one `language` train/dev/test split, which is `filewise` and `speaker independent`.

Thus we have tables:

+ `language.tunisian.train` which contains a `language` column with the language info

+ `language.tunisian.train` which contains a `language` column with the language info

**Comment by frankenjoe** [comment]
> And I thought the best way to combine that with audbenchmark is use segmentation to index the three splits. This worked in the past, but apparently not anymore

Yes, they dropped support for it in pandas: ""Passing list-likes to .loc or [] with any missing labels is no longer supported."

**Comment by hagenw** [comment]
In your example above, there should be a workaround.
You can simply combine the two tables `segmentation` and `language.tunisian.test` and remove all `NaN` entries for language afterwards.

**Comment by frankenjoe** [comment]
Ok, so you suggest we change this in `audbenchmark`?

**Comment by hagenw** [comment]
E.g.

```python
db = audformat.testing.create_db(minimal=True)
db.schemes['int'] = audformat.Scheme(int)
audformat.testing.add_table(
    db,
    'files',
    'filewise',
    num_files=[0, 1],
)
print(db['files'].get())
audformat.testing.add_table(
    db,
    'segments',
    'segmented',
    num_files=[1, 2],
)
db['segments'].df.drop(columns='int', inplace=True)
print(db['segments'].get())
df = (db['files'] + db['segments']).get()
print(df.dropna())
```

This results in

```
file              
audio/000.wav   49
audio/001.wav   41
Empty DataFrame
Columns: []
Index: [(audio/001.wav, 0 days 00:00:00.643964305, 0 days 00:00:01.001166338), (audio/001.wav, 0 days 00:00:01.730510220, 0 days 00:00:03.174225264), (audio/001.wav, 0 days 00:00:03.188945077, 0 days 00:00:03.403968566), (audio/001.wav, 0 days 00:00:03.408657089, 0 days 00:00:04.074485414), (audio/001.wav, 0 days 00:00:04.828579892, 0 days 00:00:04.897733690), (audio/002.wav, 0 days 00:00:00.346898249, 0 days 00:00:00.816321060), (audio/002.wav, 0 days 00:00:01.505234848, 0 days 00:00:01.867146572), (audio/002.wav, 0 days 00:00:02.819310015, 0 days 00:00:03.162635448), (audio/002.wav, 0 days 00:00:03.258761859, 0 days 00:00:04.129084797), (audio/002.wav, 0 days 00:00:04.250618341, 0 days 00:00:04.409905653)]
                                                                   int
file          start                     end                           
audio/000.wav 0 days 00:00:00           NaT                         41
audio/001.wav 0 days 00:00:00.643964305 0 days 00:00:01.001166338   41
              0 days 00:00:01.730510220 0 days 00:00:03.174225264   41
              0 days 00:00:03.188945077 0 days 00:00:03.403968566   41
              0 days 00:00:03.408657089 0 days 00:00:04.074485414   41
audio/002.wav 0 days 00:00:04.250618341 0 days 00:00:04.409905653   49
```

**Comment by hagenw** [comment]
> Ok, so you suggest we change the way we apply `index` in `audbenchmark`?

There we can do the same. Combine two tables and use a mapper to remove `NaN` entries.

I agree that it feels more intuitive to use `index`, but I'm a little bit skeptical if it is a good idea to silentely remove missing files instead of raising an error.

**Comment by hagenw** [comment]
Mh, it seems I discovered another bug:

```
file          start                     end                           
audio/000.wav 0 days 00:00:00           NaT                         41
audio/001.wav 0 days 00:00:00.643964305 0 days 00:00:01.001166338   41
              0 days 00:00:01.730510220 0 days 00:00:03.174225264   41
              0 days 00:00:03.188945077 0 days 00:00:03.403968566   41
              0 days 00:00:03.408657089 0 days 00:00:04.074485414   41
audio/002.wav 0 days 00:00:04.250618341 0 days 00:00:04.409905653   49
```
is not the expected result.

It should have been:

```
file          start                     end                           
audio/000.wav 0 days 00:00:00           NaT                         49
audio/001.wav 0 days 00:00:00.643964305 0 days 00:00:01.001166338   41
              0 days 00:00:01.730510220 0 days 00:00:03.174225264   41
              0 days 00:00:03.188945077 0 days 00:00:03.403968566   41
              0 days 00:00:03.408657089 0 days 00:00:04.074485414   41
```

**Comment by frankenjoe** [comment]
Hehe, just discovered the same problem :)

**Comment by frankenjoe** [comment]
> There we can do the same. Combine two tables and use a mapper to remove NaN entries.

Ah yeah, good idea. Then we don't have to change anything :)

**Comment by hagenw** [comment]
Maybe it's due to the fact that `db['segments']` has no column?

If I do the following it simply fails:

```python
>>> (db['segments'] + db['files']).get()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-4aaf5e551cef> in <module>
----> 1 df = (db['segments'] + db['files']).get()

~/git/audeering/audformat/audformat/core/table.py in __add__(self, other)
    846         # concatenate frames
    847         df = utils.concat([df_self, df_other])
--> 848         df.columns = df_columns
    849 
    850         # create table

~/.envs/audformat/lib/python3.6/site-packages/pandas/core/generic.py in __setattr__(self, name, value)
   5152         try:
   5153             object.__getattribute__(self, name)
-> 5154             return object.__setattr__(self, name, value)
   5155         except AttributeError:
   5156             pass

pandas/_libs/properties.pyx in pandas._libs.properties.AxisProperty.__set__()

~/.envs/audformat/lib/python3.6/site-packages/pandas/core/generic.py in _set_axis(self, axis, labels)
    562     def _set_axis(self, axis: int, labels: Index) -> None:
    563         labels = ensure_index(labels)
--> 564         self._mgr.set_axis(axis, labels)
    565         self._clear_item_cache()
    566 

~/.envs/audformat/lib/python3.6/site-packages/pandas/core/internals/managers.py in set_axis(self, axis, new_labels)
    225         if new_len != old_len:
    226             raise ValueError(
--> 227                 f"Length mismatch: Expected axis has {old_len} elements, new "
    228                 f"values have {new_len} elements"
    229             )

ValueError: Length mismatch: Expected axis has 1 elements, new values have 2 elements
```

**Comment by hagenw** [comment]
> > There we can do the same. Combine two tables and use a mapper to remove NaN entries.
> 
> Ah yeah, good idea. Then we don't have to change anything :)

yes and no, I think we urgently need to fix `+` for tables.

**Comment by frankenjoe** [comment]
I meant not change anything in `audbenchmark ` : )

**Comment by ATriantafyllopoulos** [comment]
> Maybe it's due to the fact that `db['segments']` has no column?

Oh yeah, I forgot to say :P Since `segmentation` did not need any column, I simply created an empty table with an index.

**Comment by frankenjoe** [comment]
> yes and no, I think we urgently need to fix + for tables.

We also have #15, so maybe we should start by defining what output we would expect in specific cases.

**Comment by frankenjoe** [comment]
> Oh yeah, I forgot to say :P Since segmentation did not need any column, I simply created an empty table with an index.

Yes, and I think that is a valid use-case we should support.

**Comment by ATriantafyllopoulos** [comment]
Btw. both the examples you listed above work for me with `audata`:

E.g. Johannes':

```python
db = audata.testing.create_db(minimal=True)
db.schemes['int'] = audata.Scheme(audata.define.DataType.INTEGER)
audata.testing.add_table(
    db,
    'files',
    'filewise',
    num_files=[0, 1],
)
print(db['files'].get())
audata.testing.add_table(
    db,
    'segments',
    'segmented',
    num_files=[1, 2],
)
print(db['segments'].get())
df = db['files'].get(index=db['segments'].index)
print(df)
```

```
audata==0.7.2
pandas==1.1.4
```

**Comment by frankenjoe** [comment]
Ah right. Now I remember that I changed the implementation of `get()` in `audformat`. I think before it was only raising an error if your requested non-existing segments from a segmented table. But I found it more consistent to also raise an error for non-existing files when you request segments from a filewise table. And I agree with @hagenw that we should not allow to request with an index that has missing entries and that the solution using `+` should be used. Unfortunately, the implementation of `+` seems to be buggy.

**Comment by ATriantafyllopoulos** [comment]
But what will `audbenchmark` use? Cause the whole point is to use this with `audbenchmark`..

**Comment by hagenw** [comment]
> But what will `audbenchmark` use? Cause the whole point is to use this with `audbenchmark`..

As stated implicetly above we can use `+` together with a `NaN` mapper in audbenchmark to achieve the desired results.
But as pointed out here, we need to fix `+` first.

**Comment by frankenjoe** [comment]
Another solution would be to make sure we remove non-existing entries in `audbenchmark` before we call `get(index)`.

**Comment by frankenjoe** [comment]
(We still need to fix `+` of course:)

**Comment by frankenjoe** [comment]
As a first step I created #43, which introduces `utils.intersect()` and provides another solution to the described problem (and hence we can use to fix the problem `audbenchmark`, too):

```
...
index = audformat.utils.intersect([db['files'].index, db['segments'].index])
df = db['files'].get(index=index)
```
```
               int
file              
audio/000.wav   36
audio/001.wav   96
                                                                   int
file          start                     end                           
audio/001.wav 0 days 00:00:00.907926738 0 days 00:00:01.121739478   34
              0 days 00:00:01.768977288 0 days 00:00:01.936853388   12
              0 days 00:00:02.248574773 0 days 00:00:02.516132523   50
              0 days 00:00:03.008089160 0 days 00:00:03.498627786   80
              0 days 00:00:03.931850534 0 days 00:00:04.992118610   56
audio/002.wav 0 days 00:00:00.999003857 0 days 00:00:01.044320261   55
              0 days 00:00:01.659894093 0 days 00:00:02.137916863   32
              0 days 00:00:02.358737267 0 days 00:00:02.845489050   55
              0 days 00:00:03.426775266 0 days 00:00:04.086356131   74
              0 days 00:00:04.862977210 0 days 00:00:04.963463293   86
```

**Comment by hagenw** [comment]
I see the advantage of first calculating the intersection, but I'm not too happy if `audbenchmark` uses `index` differently than `audformat`. So maybe we integrate it directly into `get()`? Is of course also not ideal as it breaks backward compatibility.

**Comment by frankenjoe** [comment]
>So maybe we integrate it directly into get()?

I would leave it to the user to call `intersect()` first. This way she is aware that some entries might be removed, which is better than silently remove them. 

>  but I'm not too happy if audbenchmark uses index differently than audformat. 

I would say in this case it is ok, cause the user cannot call `intersect()`. We should add a note in the docstring of course.

**Comment by hagenw** [comment]
> > So maybe we integrate it directly into get()?
> 
> I would leave it to the user to call `intersect()` first. This way she is aware that some entries might be removed, which is better than silently remove them.
> 
> > but I'm not too happy if audbenchmark uses index differently than audformat.
> 
> I would say in this case it is ok, cause the user cannot call `intersect()`. We should add a note in the docstring of course.

OK, fine with me.

**Comment by frankenjoe** [comment]
Conclusion:

- We decided to stay with the behavoiur that an error is raised if `get()` is called with an index with non-matching files/segments
- To avoid the error the user can call `audformat.utils.intersect()` first

I suggest we can close this issue.

**Comment by frankenjoe** [comment]
I now created https://github.com/audeering/audformat/issues/46 to track the bug we found earlier, and will close.
