### ISSUE TITLE
utils.read_csv doesn't recognize format

### ISSUE THREAD

**Issue by felixbur** [audeering/audformat#420]
Hi, I want to read in the attached file 
[train.csv](https://github.com/audeering/audformat/files/15092129/train.csv)

with 
```
df = audformat.utils.read_csv(data_file)
```
but get back a Series, no error:
```
type(df)
<class 'pandas.core.series.Series'>
```
it works as expected with pandas.read_csv()

**Comment by hagenw** [comment]
If only one column is present in the data, it returns a series. You can convert to a dataframe with:

```python
y = audformat.utils.read_csv("train.csv")
df = y.to_frame()
```

Or if it should be a dataframe independent of the number of columns:
```python
obj = audformat.utils.read_csv("train.csv")
if isinstance(obj, pd.Series):
    df = obj.to_frame()
else:
    df = obj
```

**Comment by hagenw** [comment]
The current behavior is not written in the text of the corresponding docstring, but indicated by the return types:

![image](https://github.com/audeering/audformat/assets/173624/61660b7d-7d88-4ea8-976e-2684418e36fe)
