### ISSUE TITLE
Introduce Table.update()

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audformat#48]
Let's have a look at the following example:

```python
db1 = audformat.testing.create_db(minimal=True)
db1.schemes['int'] = audformat.Scheme(int)
audformat.testing.add_table(db1, 'table', 'filewise')

db2 = audformat.testing.create_db(minimal=True)
db2.schemes['str'] = audformat.Scheme(str)
audformat.testing.add_table(db2, 'table', 'filewise')

audformat.utils.concat(
    [
        db1['table'].df,
        db2['table'].df
    ],
)
```
```
               int         str
file                          
audio/001.wav   47  NhDdzJX0YA
audio/002.wav   43  qdd5Onf25M
audio/003.wav   76  UIUHk0dGdi
audio/004.wav   97  WCXPkAxL5M
audio/005.wav   25  Aos20DyoUo
```

As we see we have successfully combined tables from two different database using `audformat.utils.concat()`.

Hence, a user might be surprised to learn that adding the two tables with `+` raises an error:

```python
(db1['table'] + db2['table']).get()
```
```
Bad column ID 'str', expected one of ['int']
```

The reason is that the new `Table` we create is actually assigned to `db1`:

https://github.com/audeering/audformat/blob/c045b928ddab9fbb9fc4508b0d4ca242c5f313cb/audformat/core/table.py#L795

But at the same time, we assign the the second column to scheme `str`, which is only known by `db2`:

https://github.com/audeering/audformat/blob/c045b928ddab9fbb9fc4508b0d4ca242c5f313cb/audformat/core/table.py#L790

So currently we can only safely combine tables with `+` from the same database. To overcome this limitation I suggest to not assign the new table to `db1` and set the `scheme_id` and `rater_id` of all columns to `None`. Then we can safely do:

```python
(db1['table'] + db2['table']).get()
```
```
               int         str
file                          
audio/001.wav   49  vaRA2y1rj4
audio/002.wav   42  IhpThA81cj
audio/003.wav   51  2oRdTHlYNr
audio/004.wav   31  ePZfabVHvd
audio/005.wav    5  FiZYPYcQZI
```

The only downside is that if we do:

```python
db['table1'] = db['table1'] + db['table2']  # removes scheme and rater from table1
```

we actually remove the scheme and rater information from `table1`.

Therefore I suggest to introduce a new function `Table.update()` for this use-case:

```python
db['table1'].update(db['table2'])
```

The advantage here is that we don't have a detached table as an intermediate result so we can keep scheme and rater information, and we can even copy missing schemes/raters from the other table to `db` so that also the following works:

```python
db1['table'].update(db2['table'])  # copy missing schemes and raters used in db2['table'] to db1
```

---

@hagenw please comment and if you agree I will prepare a MR

**Comment by frankenjoe** [comment]
I suggest that we also support:

```python
db1['table'].update(db2['table'], overwrite_values=True)
```

And in that case we overwrite overlapping values by `db2['table']`. This might be quite handy if we want to update labels in a Table.

**Comment by hagenw** [comment]
I'm not in favor of destroying
```python
db['table1'] + db['table2']
```
I think I would simply forbid doing:
```python
db1['table'] + db2['table']
```
But instead raising an error and pointing the user to `audformat.utils.concat` instead?

**Comment by frankenjoe** [comment]
We are not destroying `db['table1'] + db['table2']`, but the current implementation of setting a `db` object to a detached table simply does not make sense.

**Comment by frankenjoe** [comment]
Most of the time we are anyway using doing `(db['table1'] + db['table2']).get()` and not assigning it back to a database. It's anyway not working properly for the latter use-case as it will fail if the two tables are not from the same database. And for that use-case we introduce `Table.update()`. To me that makes a lot of sense.

**Comment by hagenw** [comment]
> We are not destroying `db['table1'] + db['table2']`, but the current implementation of setting a `db` object to a detached table simply does not make sense.

Before you said:
> To overcome this limitation I suggest to not assign the new table to `db1` and set the `scheme_id` and `rater_id` of all columns to `None`

So, I thought it is working at the moment, but you would change it to a "detached" table?

**Comment by hagenw** [comment]
What I'm also not completely getting here: why do we need `Table.update()` and get not simply change `Table.__add__()` to behave that way,  because of the new `overwrite` argument?

**Comment by frankenjoe** [comment]
> So, I thought it is working at the moment, but you would change it to a "detached" table?

Currently, if you do `table = db1['table'] + db2['table']` it will set `table._db == db1`, even though `table` is not even part of `db1`. Only in the specific use-case where you do `db1['table_new'] =  db1['table'] + db2['table']` it would make sense. But then it also fails if `db2['table']` references a scheme that is not in `db1`.

**Comment by frankenjoe** [comment]
> why do we need Table.update() and get not simply change Table.__add__() to behave that way, because of the new overwrite argument?

The difference is that when we do `db['table'].update()`, we update an existing table of `db` and the result cannot be assigned to another database e.g.. But  `Table.__add__()` always returns a table object the user can either add to a database at all or add any other database.

**Comment by frankenjoe** [comment]
But maybe it gets clearer if I prepare a MR that we can directly see the changes and test it?

**Comment by hagenw** [comment]
> > why do we need Table.update() and get not simply change Table.**add**() to behave that way, because of the new overwrite argument?
> 
> The difference is that when we do `db['table'].update()`, we update an existing table of `db` and the result cannot be assigned to a different database. But `Table.__add__()` returns a table object the user can assign to any other database (or to none).

Ok, that difference seems to make sense, so yes, go ahead and prepare a pull request.
