### ISSUE TITLE
Make objects like Table and Column independent of database

### ISSUE THREAD

**Issue by hagenw** [audeering/audformat#50]
At the moment a `Table` stores inside its object that it is connected to a database.
This leads to several problems when doing something like `table1 + table2` which would return a table that is not connected to any database.
This might be ok as users just want to access the data. The downside of detached tables is that we will loose scheme informations of the underlying columns.
See also the discussion in https://github.com/audeering/audformat/pull/49#discussion_r581912060

If we would change the current behavior, it would break the API.

**Comment by hagenw** [comment]
We now also have `audformat.Database.update()` to add another table to an existing one that will then stay inside the current database.
This does completely solve this issue, but I would argue sufficiently enough as we won't break the API and change it in the near future.

**Comment by frankenjoe** [comment]
I agree
