### ISSUE TITLE
Add data from a Series with non-matching dtype

### ISSUE THREAD

**Issue by hagenw** [audeering/audformat#54]
At the moment you can experience the following error if you try to add data from a `pd.Series` that has a `dtype` that does not match the one specified in the corresponding scheme of the column:

```python
>>> db['answer']['rating'].set(df.rating)
...
TypeError: '<' not supported between instances of 'NoneType'/'float' and 'str'
```

The problem is that a user might not be able to figure out what is wrong by herself/himself.
I see two solutions:

1. Add a custom error message that points to the workaround of using `list()` or setting the correct `dtype`
2. Do some kind of conversion (e.g. using `list()`) internally and ignore the `dtype` setting of the `pd.Series`

**Comment by hagenw** [comment]
I'm not sure if this error exists any longer:

```python
import pandas as pd
import numpy as np

import audformat


db = audformat.Database('test')
db.schemes['test'] = audformat.Scheme(str)
db['table'] = audformat.Table(index=audformat.filewise_index(['a', 'b']))
db['table']['test'] = audformat.Column(scheme_id='test')

df = pd.DataFrame(
    data=['a', np.NaN],
    index=audformat.filewise_index(['a', 'b']),
    columns=['test'],
)
db['table']['test'].set(df.test)

db['table']._df
```

This returns

```
     test
file     
a       a
b     NaN
```

**Comment by frankenjoe** [comment]
I think it's good if it allows `np.NaN` here. But what happens if you pass e.g. `data=['a', 1.0]`? In that case I would expect to get an error.

**Comment by hagenw** [comment]
You are right, but this seems to be another issue to me, could you please open an issue for that ;)

**Comment by frankenjoe** [comment]
Ah, but when we set the type of the scheme to `int` and pass a string, then we actually get an error:

```
db = audformat.Database('test')
db.schemes['test'] = audformat.Scheme(float)
db['table'] = audformat.Table(index=audformat.filewise_index(['a', 'b']))
db['table']['test'] = audformat.Column(scheme_id='test')

df = pd.DataFrame(
    data=['a', 1.0],
    index=audformat.filewise_index(['a', 'b']),
    columns=['test'],
)
db['table']['test'].set(df.test)
db['table'].get()
```
```
ValueError: could not convert string to float: 'a'
```

I guess it's because the dtype of a string column is `object`, which support any time.

**Comment by frankenjoe** [comment]
So I think we can stay with this issue.

**Comment by hagenw** [comment]
OK, but regarding this issue, I think we can close it as I can no longer reproduce the problem reported in the first place. I also remember that we implemented something to avoid having to use `list()` all the time with `set()`?

**Comment by frankenjoe** [comment]
OK, then let's close this issue and I will create a new one.
