### ISSUE TITLE
audformat.testing.create_audio_files does not set db.root

### ISSUE THREAD

**Issue by hagenw** [audeering/audformat#72]
Example:

```python
import audformat.testing

db = audformat.testing.create_db(minimal=True)
db.raters['rater'] = audformat.Rater()
db.schemes['str'] = audformat.Scheme(str)
audformat.testing.add_table(db, 'table', 'segmented', columns={'str': ('str', 'rater')})
audformat.testing.create_audio_files(db, './database', file_duration='0.1s')

db.root
```

results in

```
```

But it should return `audeer.safe_path('./database')` instead.

**Comment by frankenjoe** [comment]
You have to save the database first.

**Comment by frankenjoe** [comment]
Maybe `audformat.testing.create_audio_files()` should fail if the database has not been saved yet?

**Comment by hagenw** [comment]
Something has to happen.

It's in general conceptual not that easy that parts of a database can consists in memory only, whereas other parts cannot.

**Comment by frankenjoe** [comment]
Currently the docstring for `root` says: "root: root folder where the database is (or will be) stored".

**Comment by frankenjoe** [comment]
But I agree it would be better to remove `root` and instead raise an error if the database has not been stored yet.

**Comment by frankenjoe** [comment]
Now that we have `Database.root` we can implement it. Before it wasn't possible since there was no way to know if a database has been stored or not.
