### ISSUE TITLE
NaT is not returned when indexing an index

### ISSUE THREAD

**Issue by hagenw** [audeering/audformat#87]
To me the following looks like a `pandas` bug:

```python
>>> idx = audformat.segmented_index(['a'], [0], [pd.NaT])
>>> idx
MultiIndex([('a', '0 days', NaT)],
           names=['file', 'start', 'end'])
>>> idx.get_level_values('end')
TimedeltaIndex([NaT], dtype='timedelta64[ns]', name='end', freq=None)
>>> idx[0]
('a', Timedelta('0 days 00:00:00'), nan)
```

I would have expected that `idx[0]` should return
```
('a', Timedelta('0 days 00:00:00'), Timedelta(NaT))
```
or if this is possible
```
('a', Timedelta('0 days 00:00:00'), NaT)
```

I don't think that this will have big implications, but it took me a while to fix a test that was failing due to the returned `nan` value.

It might be that `pandas` don't consider it as a bug as the following still works:

```python
>>> pd.isnull(idx[0][2])
True
```
so it doesn't matter if it is `NaT` or `nan`.

But the problem is that we loose information of the object as timedelta and datetime return the same and some other functions might then interpret it as a datetime index and fail.

**Comment by frankenjoe** [comment]
Seems not like something we can solve, so I propose we close the issue.

**Comment by hagenw** [comment]
I agree, we cannot tackle every inconsistency that `pandas` shows for `timedelta` ;)
