### ISSUE TITLE
DOC: update conventions on file duration

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audformat#88]
We currently recommend to store file duration:

https://audeering.github.io/audformat/data-conventions.html#file-duration-and-temporal-data

However, as discussed in [audb](https://github.com/audeering/audb/issues/113) we can get the file duration from the dependencies. So maybe we should remove file duration from the conventions.

**Comment by hagenw** [comment]
Yes, I agree. We should extend the documentation on how to get duration information and remove duration from the scheme.

What is a little bit tricky though is that some duration information is available already if you only use `audformat` and other only if you use it together with `audb`. But I guess, the main purpose of `audformat` is anyway to use it together with `audb`?
So I would first focus on extend the documentation in `audb`.

**Comment by frankenjoe** [comment]
> So I would first focus on extend the documentation in audb.

Agree.

**Comment by hagenw** [comment]
Done in #96.
